### PR TITLE
chore(package): remove unused dependency

### PR DESCRIPTION
**Pull request by JLHwung**

### CODE REVIEW

**Comment by ZebraFlesh** [comment]
This is actually used in the `scripts` block of package.json: https://github.com/motiz88/git-exec-and-restage/blob/master/package.json#L14

**Comment by JLHwung** [comment]
@ZebraFlesh semantic-release-cli is used to setup a project using semantic-release. To use semantic-release in scripts it suffices to add semantic-release to devDependencies.

**Comment by ZebraFlesh** [comment]
Ah I see that now. Going to close my PR in favor of this one.

**Comment by ZebraFlesh** [comment]
This will resolve #21

**Pull request merged**
